---
- name: Ensure dotfiles repository is cloned.
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- import_tasks: parse.yml

- name: Ensure all dotfiles in are links.
  ansible.builtin.command: "ls -F {{ item.dest }}"
  failed_when: false
  check_mode: false
  changed_when: false
  register: existing_dotfile_info
  with_items: "{{ parsed_links }}"

- name: Remove existing dotfiles if replacement is being linked.
  file:
    path: "~/{{ parsed_links[item.0] }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Link dotfiles into home folder.
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
    state: link
    mode: 0755
  become: false
  with_items: "{{ parsed_links }}"

- import_tasks: tmux.yml

